services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: adm
    restart: always

  flask-rest-api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongodb
    volumes:
      - .:/app
